pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.6
      architecture: 'x64'
  - script: |
      python -m pip install --upgrade pip setuptools wheel django
      pip install -r requirements.txt
    workingDirectory: '$(System.DefaultWorkingDirectory)/AzTFServerless'
    displayName: 'Install prerequisites'
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/AzTFServerless'
      includeRootFolder: false
      archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish files'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)'
      name: 'drop'
